### ISSUE TITLE
Wrong index for iterating over boxes

### ISSUE THREAD

**Issue by gieses** [Jhruzik/ImmobilienScout24.de-Crawler#2]
Thanks for your crawler! Saved me a lot of work. I think your indexing is wrong at

```
 for i in range(1,len(rawdata_extract)):
        try:
            price.append(rawdata_extract[i].find_all("dd")[0].get_text().strip())#extract price
        except:
price.append(None)
```

the indexing should start at 0.
Cheers,

**Comment by Jhruzik** [comment]
You are 100% correct! Since I use R for most of my work, I slipped in the 1 to n indexing. I will correct it.

Thank you so much.
